// Mocks generated by Mockito 5.3.2 from annotations
// in variacao_ativo/test/app/modules/active_variation/data/repositories/active_variation_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:variacao_ativo/app/modules/active_variation/data/datasources/active_variation_datasource.dart'
    as _i3;
import 'package:variacao_ativo/app/modules/active_variation/data/models/active_model.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeActiveModel_0 extends _i1.SmartFake implements _i2.ActiveModel {
  _FakeActiveModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IActiveVariationDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIActiveVariationDataSource extends _i1.Mock
    implements _i3.IActiveVariationDataSource {
  MockIActiveVariationDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ActiveModel> getActiveVariation(String? activeName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveVariation,
          [activeName],
        ),
        returnValue: _i4.Future<_i2.ActiveModel>.value(_FakeActiveModel_0(
          this,
          Invocation.method(
            #getActiveVariation,
            [activeName],
          ),
        )),
      ) as _i4.Future<_i2.ActiveModel>);
}
